version: 2.1 
jobs:
  compile:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential libncurses5-dev bzip2 git bc
           git clone --depth=1 https://github.com/yuukaos/android_kernel_samsung_msm8916.git -b lineage-17.1
           wget https://releases.linaro.org/components/toolchain/binaries/latest-7/arm-linux-gnueabihf/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf.tar.xz
           tar -xvf gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf.tar.xz
           cd android_kernel_samsung_msm8916
           bash build_kernel.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
